In [82]:
import pandas as pd

In [83]:
country_data = pd.read_csv('life_expectancy_by_country.csv')
country_data

      country_code country_name  year   value
0              ABW        Aruba  1960  64.152
1              ABW        Aruba  1961  64.537
2              ABW        Aruba  1962  64.752
3              ABW        Aruba  1963  65.132
4              ABW        Aruba  1964  65.294
...            ...          ...   ...     ...
15201          ZWE     Zimbabwe  2016  60.306
15202          ZWE     Zimbabwe  2017  60.709
15203          ZWE     Zimbabwe  2018  61.414
15204          ZWE     Zimbabwe  2019  61.292
15205          ZWE     Zimbabwe  2020  61.124

[15206 rows x 4 columns]

In [84]:
region_list = ['Africa Eastern and Southern', 'Africa Western and Central', 'Central Europe and the Baltics', 'Caribbean small states', 'East Asia & Pacific', 'Europe & Central Asia', 'Euro area', 'European Union', 'Latin America & Caribbean', 'Middle East & North Africa', 'North America', 'Pacific island small states', 'South Asia', 'Sub-Saharan Africa']

In [85]:
# remove rows that are not in the region list
country_data = country_data[country_data['country_name'].isin(region_list)]
country_data

      country_code                 country_name  year      value
61             AFE  Africa Eastern and Southern  1960  44.085552
62             AFE  Africa Eastern and Southern  1961  44.386697
63             AFE  Africa Eastern and Southern  1962  44.752182
64             AFE  Africa Eastern and Southern  1963  44.913159
65             AFE  Africa Eastern and Southern  1964  45.479043
...            ...                          ...   ...        ...
12347          SSF           Sub-Saharan Africa  2016  60.069021
12348          SSF           Sub-Saharan Africa  2017  60.477135
12349          SSF           Sub-Saharan Africa  2018  60.863024
12350          SSF           Sub-Saharan Africa  2019  61.244287
12351          SSF           Sub-Saharan Africa  2020  60.848891

[854 rows x 4 columns]

In [86]:
# remove rows that are not years 1960, 1980, 2000, 2020
country_data = country_data[country_data['year'].isin([1960, 1980, 2000, 2020])]

In [87]:
# reset index
country_data = country_data.reset_index(drop=True)
country_data

   country_code                    country_name  year      value
0           AFE     Africa Eastern and Southern  1960  44.085552
1           AFE     Africa Eastern and Southern  1980  49.636538
2           AFE     Africa Eastern and Southern  2000  51.964481
3           AFE     Africa Eastern and Southern  2020  63.313856
4           AFW      Africa Western and Central  1960  37.845152
5           AFW      Africa Western and Central  1980  47.015239
6           AFW      Africa Western and Central  2000  50.221954
7           AFW      Africa Western and Central  2020  57.226373
8           CEB  Central Europe and the Baltics  1960  67.933952
9           CEB  Central Europe and the Baltics  1980  69.888985
10          CEB  Central Europe and the Baltics  2000  72.719725
11          CEB  Central Europe and the Baltics  2020  76.144034
12          CSS          Caribbean small states  1960  61.952121
13          CSS          Caribbean small states  1980  67.350540
14          CSS          Caribbean small states  2000  69.575544
15          CSS          Caribbean small states  2020  72.574882
16          EAS             East Asia & Pacific  1960  41.641928
17          EAS             East Asia & Pacific  1980  64.724662
18          EAS             East Asia & Pacific  2000  71.552687
19          EAS             East Asia & Pacific  2020  76.762681
20          ECS           Europe & Central Asia  1960  67.514086
21          ECS           Europe & Central Asia  1980  70.284901
22          ECS           Europe & Central Asia  2000  73.132098
23          ECS           Europe & Central Asia  2020  77.025324
24          EMU                       Euro area  1960  69.284294
25          EMU                       Euro area  1980  73.580654
26          EMU                       Euro area  2000  78.270835
27          EMU                       Euro area  2020  81.537122
28          EUU                  European Union  1960  69.037606
29          EUU                  European Union  1980  72.789606
30          EUU                  European Union  2000  77.075317
31          EUU                  European Union  2020  80.465037
32          LCN       Latin America & Caribbean  1960  55.146440
33          LCN       Latin America & Caribbean  1980  63.681366
34          LCN       Latin America & Caribbean  2000  71.227714
35          LCN       Latin America & Caribbean  2020  73.038409
36          MEA      Middle East & North Africa  1960  44.757573
37          MEA      Middle East & North Africa  1980  58.571006
38          MEA      Middle East & North Africa  2000  69.282178
39          MEA      Middle East & North Africa  2020  72.951079
40          NAC                   North America  1960  69.893606
41          NAC                   North America  1980  73.752431
42          NAC                   North America  2000  76.881996
43          NAC                   North America  2020  77.741163
44          PSS     Pacific island small states  1960  54.526438
45          PSS     Pacific island small states  1980  62.898881
46          PSS     Pacific island small states  2000  67.400452
47          PSS     Pacific island small states  2020  69.470610
48          SAS                      South Asia  1960  45.104840
49          SAS                      South Asia  1980  53.759807
50          SAS                      South Asia  2000  62.892973
51          SAS                      South Asia  2020  69.748331
52          SSF              Sub-Saharan Africa  1960  41.422546
53          SSF              Sub-Saharan Africa  1980  48.572456
54          SSF              Sub-Saharan Africa  2000  51.264545
55          SSF              Sub-Saharan Africa  2020  60.848891

In [88]:
# add columns 1960, 1980, 2000, 2020 with values from value column corresponding to year
country_data['1960'] = country_data['value'][country_data['year'] == 1960]

In [89]:
country_data['1980'] = country_data['value'][country_data['year'] == 1980]
country_data['2000'] = country_data['value'][country_data['year'] == 2000]
country_data['2020'] = country_data['value'][country_data['year'] == 2020]

In [90]:
country_data

,country_code,country_name,year,value,1960,1980,2000,2020
0,AFE,Africa Eastern and Southern,1960,44.085552,44.085552,NaN,NaN,NaN
1,AFE,Africa Eastern and Southern,1980,49.636538,NaN,49.636538,NaN,NaN
2,AFE,Africa Eastern and Southern,2000,51.964481,NaN,NaN,51.964481,NaN
3,AFE,Africa Eastern and Southern,2020,63.313856,NaN,NaN,NaN,63.313856
4,AFW,Africa Western and Central,1960,37.845152,37.845152,NaN,NaN,NaN
5,AFW,Africa Western and Central,1980,47.015239,NaN,47.015239,NaN,NaN
6,AFW,Africa Western and Central,2000,50.221954,NaN,NaN,50.221954,NaN
7,AFW,Africa Western and Central,2020,57.226373,NaN,NaN,NaN,57.226373
8,CEB,Central Europe and the Baltics,1960,67.933952,67.933952,NaN,NaN,NaN
9,CEB,Central Europe and the Baltics,1980,69.888985,NaN,69.888985,NaN,NaN
10,CEB,Central Europe and the Baltics,2000,72.719725,NaN,NaN,72.719725,NaN
11,CEB,Central Europe and the Baltics,2020,76.144034,NaN,NaN,NaN,76.144034
12,CSS,Caribbean small states,1960,61.952121,61.952121,NaN,NaN,NaN
13,CSS,Caribbean small states,1980,67.350540,NaN,67.350540,NaN,NaN
14,CSS,Caribbean small states,2000,69.575544,NaN,NaN,69.575544,NaN
15,CSS,Caribbean small states,2020,72.574882,NaN,NaN,NaN,72.574882
16,EAS,East Asia & Pacific,1960,41.641928,41.641928,NaN,NaN,NaN
17,EAS,East Asia & Pacific,1980,64.724662,NaN,64.724662,NaN,NaN
18,EAS,East Asia & Pacific,2000,71.552687,NaN,NaN,71.552687,NaN
19,EAS,East Asia & Pacific,2020,76.762681,NaN,NaN,NaN,76.762681
20,ECS,Europe & Central Asia,1960,67.514086,67.514086,NaN,NaN,NaN
21,ECS,Europe & Central Asia,1980,70.284901,NaN,70.284901,NaN,NaN
22,ECS,Europe & Central Asia,2000,73.132098,NaN,NaN,73.132098,NaN
23,ECS,Europe & Central Asia,2020,77.025324,NaN,NaN,NaN,77.025324
24,EMU,Euro area,1960,69.284294,69.284294,NaN,NaN,NaN
25,EMU,Euro area,1980,73.580654,NaN,73.580654,NaN,NaN
26,EMU,Euro area,2000,78.270835,NaN,NaN,78.270835,NaN
27,EMU,Euro area,2020,81.537122,NaN,NaN,NaN,81.537122
28,EUU,European Union,1960,69.037606,69.037606,NaN,NaN,NaN
29,EUU,European Union,1980,72.789606,NaN,72.789606,NaN,NaN
30,EUU,European Union,2000,77.075317,NaN,NaN,77.075317,NaN
31,EUU,European Union,2020,80.465037,NaN,NaN,NaN,80.465037
32,LCN,Latin America & Caribbean,1960,55.146440,55.146440,NaN,NaN,NaN
33,LCN,Latin America & Caribbean,1980,63.681366,NaN,63.681366,NaN,NaN
34,LCN,Latin America & Caribbean,2000,71.227714,NaN,NaN,71.227714,NaN
35,LCN,Latin America & Caribbean,2020,73.038409,NaN,NaN,NaN,73.038409
36,MEA,Middle East & North Africa,1960,44.757573,44.757573,NaN,NaN,NaN
37,MEA,Middle East & North Africa,1980,58.571006,NaN,58.571006,NaN,NaN
38,MEA,Middle East & North Africa,2000,69.282178,NaN,NaN,69.282178,NaN
39,MEA,Middle East & North Africa,2020,72.951079,NaN,NaN,NaN,72.951079
40,NAC,North America,1960,69.893606,69.893606,NaN,NaN,NaN
41,NAC,North America,1980,73.752431,NaN,73.752431,NaN,NaN
42,NAC,North America,2000,76.881996,NaN,NaN,76.881996,NaN
43,NAC,North America,2020,77.741163,NaN,NaN,NaN,77.741163
44,PSS,Pacific island small states,1960,54.526438,54.526438,NaN,NaN,NaN
45,PSS,Pacific island small states,1980,62.898881,NaN,62.898881,NaN,NaN
46,PSS,Pacific island small states,2000,67.400452,NaN,NaN,67.400452,NaN
47,PSS,Pacific island small states,2020,69.470610,NaN,NaN,NaN,69.470610
48,SAS,South Asia,1960,45.104840,45.104840,NaN,NaN,NaN
49,SAS,South Asia,1980,53.759807,NaN,53.759807,NaN,NaN
50,SAS,South Asia,2000,62.892973,NaN,NaN,62.892973,NaN
51,SAS,South Asia,2020,69.748331,NaN,NaN,NaN,69.748331
52,SSF,Sub-Saharan Africa,1960,41.422546,41.422546,NaN,NaN,NaN
53,SSF,Sub-Saharan Africa,1980,48.572456,NaN,48.572456,NaN,NaN
54,SSF,Sub-Saharan Africa,2000,51.264545,NaN,NaN,51.264545,NaN
55,SSF,Sub-Saharan Africa,2020,60.848891,NaN,NaN,NaN,60.848891

In [91]:
# make a new data frame with country_name and 1960, 1980, 2000, 2020 columns
country_data_new = country_data[['country_name', '1960', '1980', '2000', '2020']]

In [92]:
# remove columns 1980, 2000, 2020
country_data_1960_ = country_data_new.drop(columns=['1980', '2000', '2020'])


country_data_1980_ = country_data_new.drop(columns=['1960', '2000', '2020'])

country_data_2000_ = country_data_new.drop(columns=['1960', '1980', '2020'])

country_data_2020_ = country_data_new.drop(columns=['1960', '1980', '2000'])

In [93]:
# remove nan rows in country_data_1960_
country_data_1960_ = country_data_1960_.dropna()
# reset index
country_data_1960_ = country_data_1960_.reset_index(drop=True)

# remove nan rows in country_data_1980_
country_data_1980_ = country_data_1980_.dropna()
# reset index
country_data_1980_ = country_data_1980_.reset_index(drop=True)

# remove nan rows in country_data_2000_
country_data_2000_ = country_data_2000_.dropna()
# reset index
country_data_2000_ = country_data_2000_.reset_index(drop=True)

# remove nan rows in country_data_2020_
country_data_2020_ = country_data_2020_.dropna()
# reset index
country_data_2020_ = country_data_2020_.reset_index(drop=True)

In [94]:
country_data_2020_

                      country_name       2020
0      Africa Eastern and Southern  63.313856
1       Africa Western and Central  57.226373
2   Central Europe and the Baltics  76.144034
3           Caribbean small states  72.574882
4              East Asia & Pacific  76.762681
5            Europe & Central Asia  77.025324
6                        Euro area  81.537122
7                   European Union  80.465037
8        Latin America & Caribbean  73.038409
9       Middle East & North Africa  72.951079
10                   North America  77.741163
11     Pacific island small states  69.470610
12                      South Asia  69.748331
13              Sub-Saharan Africa  60.848891

In [95]:
# add 1960, 1980, 2000 columns to country_data_2020_
country_data_2020_['2000'] = country_data_2000_['2000']
country_data_2020_['1980'] = country_data_1980_['1980']
country_data_2020_['1960'] = country_data_1960_['1960']

country_data_2020_

                      country_name       2020       2000       1980       1960
0      Africa Eastern and Southern  63.313856  51.964481  49.636538  44.085552
1       Africa Western and Central  57.226373  50.221954  47.015239  37.845152
2   Central Europe and the Baltics  76.144034  72.719725  69.888985  67.933952
3           Caribbean small states  72.574882  69.575544  67.350540  61.952121
4              East Asia & Pacific  76.762681  71.552687  64.724662  41.641928
5            Europe & Central Asia  77.025324  73.132098  70.284901  67.514086
6                        Euro area  81.537122  78.270835  73.580654  69.284294
7                   European Union  80.465037  77.075317  72.789606  69.037606
8        Latin America & Caribbean  73.038409  71.227714  63.681366  55.146440
9       Middle East & North Africa  72.951079  69.282178  58.571006  44.757573
10                   North America  77.741163  76.881996  73.752431  69.893606
11     Pacific island small states  69.470610  67.400452  62.898881  54.526438
12                      South Asia  69.748331  62.892973  53.759807  45.104840
13              Sub-Saharan Africa  60.848891  51.264545  48.572456  41.422546

In [96]:
# Sort by 2020 column
country_data_2020_ = country_data_2020_.sort_values(by=['2020'], ascending=False)

In [97]:
# reset index
country_data_2020_ = country_data_2020_.reset_index(drop=True)

In [98]:
country_data_2020_

                      country_name       2020       2000       1980       1960
0                        Euro area  81.537122  78.270835  73.580654  69.284294
1                   European Union  80.465037  77.075317  72.789606  69.037606
2                    North America  77.741163  76.881996  73.752431  69.893606
3            Europe & Central Asia  77.025324  73.132098  70.284901  67.514086
4              East Asia & Pacific  76.762681  71.552687  64.724662  41.641928
5   Central Europe and the Baltics  76.144034  72.719725  69.888985  67.933952
6        Latin America & Caribbean  73.038409  71.227714  63.681366  55.146440
7       Middle East & North Africa  72.951079  69.282178  58.571006  44.757573
8           Caribbean small states  72.574882  69.575544  67.350540  61.952121
9                       South Asia  69.748331  62.892973  53.759807  45.104840
10     Pacific island small states  69.470610  67.400452  62.898881  54.526438
11     Africa Eastern and Southern  63.313856  51.964481  49.636538  44.085552
12              Sub-Saharan Africa  60.848891  51.264545  48.572456  41.422546
13      Africa Western and Central  57.226373  50.221954  47.015239  37.845152

In [99]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import numpy as np

from bokeh.io import output_notebook, show
from bokeh.models import ColumnDataSource, FactorRange, Legend
from bokeh.plotting import figure

import seaborn as sns

output_notebook()
from bokeh.models import Range1d
from bokeh.plotting import figure, show, output_file
table = country_data_2020_.set_index('country_name')
source = ColumnDataSource(table)

p = figure(x_range=FactorRange(factors=table.index),
           plot_width=900,
           plot_height=675,
           title='Life expectancy by region in select years', 
           x_axis_label='Region', 
           y_axis_label='Years')

cmap = sns.color_palette('pastel', len(table.columns)).as_hex()

bar = {}
items = []

for i, crime in enumerate(list(table.columns)):
    bar[crime] = p.vbar(x='country_name', 
                    top=crime, 
                    source=source, 
                    width=0.7,
                    color=cmap[i],
                    fill_alpha=0.3,
                    muted=True, 
                    muted_alpha=0.005) 
    items.append((crime, [bar[crime]]))
bar['2020'].muted = False
bar['1960'].muted = False
p.xaxis.major_label_orientation = 1
p.y_range = Range1d(0, 100)

legend = Legend(items=items)
p.add_layout(legend, 'left')    
p.legend.click_policy = 'mute'
output_file('bokeh.html')
show(p)